title: GAIMHE
description: Generative AI Models for Hybrid Educational technologies
theme: jekyll-theme-cayman
show_downloads: false

# Navigation links (optional, for themes that support it)
header_pages:
  - project.md
  - datasets.md
  - collaborations.md
  - contact.md
